### ISSUE TITLE
Enable multithreading to use std::thread: Operation not permitted

### ISSUE THREAD

**Issue by dgu123** [juanchopanza/cppblog#1]
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted (core dumped) in the queue code

**Comment by juanchopanza** [comment]
Without knowing what you did to get this error I can only speculate. I have often seen this problem when people use g++ and fail to use the -pthread flag.
But it is really up to you to figure out to enable multi-threading on your system. Or at least provide enough information so that someone can reproduce the problem.

**Comment by dgu123** [comment]
sorry it was an ide issue , it s working fine
